### ISSUE TITLE
Add Biographies for staff

### ISSUE THREAD

**Issue by jaboc83** [unsignedbytes/mnrangers#10]

**Comment by jaboc83** [comment]
Waiting for information from @mnrangers

**Comment by MNRangers** [comment]
Jill FISHER- CERTIFIED PERSONAL TRAINER,LMT, Certified Cupping Therapist
Played Basketball, Soccer, and Dance.

Enjoys competing in Marathons, relay races, and obstacles events.

Competitive Skydiver… Yes you can compete in skydiving!!

Sports have always been an important part of my life and while I’ve always been active my eating habits were less than ideal. Helping people push beyond their ‘self-limits’, push beyond their doubts, and help transform their mental/ psychological/ physical health. I get to live my dream everyday and watching people discover their dreams is all worth!!! As a former athlete, Jill is passionate about helping her patients maintain a healthy well-balanced body or return from an injury stronger than before.

Jill was born in Gardnerville, NV and moved to Minnesota in 2004 graduating from Minnetonka High School in 2005. Born from personal experience of losing 80 pounds and overcoming many injuries, Jill lives her passion by working as a Personal Trainer and a Massage Therapist.

Jill specializes in Deep Tissue, Sports Massage, Myofascial Release, and PNF (Assisted Stretching). There is no greater satisfaction then watching your patients achieve their goals, overcome adversity, and redefining their “normal”.

Special Certifications…
Nutrition Coach • Pregnancy / Children • Pilates Certified • Kickboxing/ Self- Defense • Beginning Kettle bells • TRX • Indoor water rower • PNF Stretching

**Comment by MNRangers** [comment]
Michael Wright
Former juvenile correctional officer for 6 years 

Volunteer fire fighter for 2 years before I moved to paid.

Volunteer at boys and girls club greater Houston area for 2 years

2001 state champion

NBA free agent

**Comment by jaboc83** [comment]
Closing this down to create specific tasks for remaining items
