### ISSUE TITLE
Add Content to Community Page

### ISSUE THREAD

**Issue by jaboc83** [unsignedbytes/mnrangers#17]

**Comment by MNRangers** [comment]
![second harvest heartland jan 21 2016](https://cloud.githubusercontent.com/assets/16638123/12651137/fd6b92b6-c5aa-11e5-87fb-e565444f5ea2.jpg)

**Comment by jaboc83** [comment]
Do you have some text to go with the photo as well as describe the general community outreach goal?

**Comment by MNRangers** [comment]
Minnesota Rangers team and staff helped to pack 13,750 meals in January at Second Harvest Heartland. 

I don't know- something like that?  Do you think it needs the date or ?

**Comment by jaboc83** [comment]
Date would probably be good. We can start with this.

**Comment by MNRangers** [comment]
January 21st
