### ISSUE TITLE
Need Venue Information

### ISSUE THREAD

**Issue by Jasem84** [unsignedbytes/mnrangers#19]
@mnrangers

**Comment by MNRangers** [comment]
Hopefully will know this in the next week (or two)

**Comment by MNRangers** [comment]
OXFORD COMMUNITY CENTER
270 Lexington Parkway No.
St. Paul, MN 55104

for all home games EXCEPT June 11th.

June 11th is at:
Eagan Community Center
1501 Central Pkwy
Eagan, MN 55124

All home games (at both locations) are at 1:00 pm
