### ISSUE TITLE
Inconsistent staff bios

### ISSUE THREAD

**Issue by jaboc83** [unsignedbytes/mnrangers#24]
Format is very different from one to the next and some extend well into unrelated material. Maybe move some of this info off into a staff spotlight piece or something on the Facebook page?

@mnrangers

**Comment by MNRangers** [comment]
Michael Wright, President of Basketball Operations, is the founder of Minnesota Rangers Basketball.  Michael is an NBA Free Agent with the goals of helping the gentlemen on the team not only improve themselves and their communities, but also has the intentions of helping the players gain exposure for the betterment of their athletic careers.

Latisha Moening is the Secretary on the Board of Directors as well as the Community Relations Director for the organization.   Latisha’s goals for the team vary with her different positions.  As the Community Relations Director her goals are geared more toward developing a healthy relationship between the organizations staff, players and the community.  As an owner and a board member Latisha has additional goals to help improve the players individually, as a team, and the organization itself to help boost chances of advancement in their athletic careers and a healthy future for the organization.

**Comment by jaboc83** [comment]
Looks much more consistent. We'll add this. Still waiting on some so I'll leave the 'Waiting on Rangers Staff' tag on here.  @jasem84 can you take this one on?

**Comment by jaboc83** [comment]
I created new tickets for the remaining items so I can close this.
