### ISSUE TITLE
Add player images to about section

### ISSUE THREAD

**Issue by jaboc83** [unsignedbytes/mnrangers#26]
@mnrangers  Need pics

**Comment by MNRangers** [comment]
can you put up the photos we just took for the players we do have?  and how do you want me to get those photos to you then?

**Comment by jaboc83** [comment]
Yeah, we can add those for sure. I'll keep the 'Waiting on Rangers Staff' tag there until we get them all though so we don't forget. If you email me the link to the Dropbox I should be able to grab them from there.

**Comment by MNRangers** [comment]
I don't have a drop box link - we just saved them all on the desktop
downstairs remember and put them on facebook.

On Fri, Jan 29, 2016 at 1:52 PM, Jake Moening notifications@github.com
wrote:

> Yeah, we can add those for sure. I'll keep the 'Waiting on Rangers Staff'
> tag there until we get them all though so we don't forget. If you email me
> the link to the Dropbox I should be able to grab them from there.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/unsignedbytes/mnrangers/issues/26#issuecomment-176939124
> .

## 

_Latisha R. Moening_
_Minnesota Rangers Owner/Community Relations Director_

_https://www.facebook.com/MNRangersBasketball/?fref=ts
https://www.facebook.com/MNRangersBasketball/?fref=ts_
_MNRangersCR@gmail.com MNRangersCR@gmail.com_
_701-388-8662_

**Comment by jaboc83** [comment]
That works too. I'll just grab them from the folder.

**Comment by jaboc83** [comment]
Added the pics we have for now.

**Comment by jaboc83** [comment]
Added latest pics, still missing Sam and Dee
