### ISSUE TITLE
Add times and locations for games

### ISSUE THREAD

**Issue by jaboc83** [unsignedbytes/mnrangers#27]

**Comment by jaboc83** [comment]
@mnrangers

**Comment by MNRangers** [comment]
OXFORD COMMUNITY CENTER
270 Lexington Parkway No.
St. Paul, MN 55104

for all home games EXCEPT June 11th.

June 11th is at:
Eagan Community Center
1501 Central Pkwy
Eagan, MN 55124

All home games at both locations are at 1:00 pm

**Comment by MNRangers** [comment]
Emailed Jake some of the other game times and locations

**Comment by jaboc83** [comment]
Updated with information that is available
