### ISSUE TITLE
Fix Jill's Bio

### ISSUE THREAD

**Issue by jaboc83** [unsignedbytes/mnrangers#32]
Make it consistent length and style as rest of bios

**Comment by MNRangers** [comment]
Jill Fisher
Team Strength & Conditioning Coach

Jill Fisher is the head trainer and a member of the coaching staff for the Minnesota Rangers. Jill works with each athlete to identify their strengths and weaknesses, personalizes conditioning plans, and leads team workouts to promote team cohesiveness. Jill's goals for the team is to educate the athletes about the importance of strength training, to work with the coaches to achieve success as a basketball team, and for the organization to give back to the community.
