### ISSUE TITLE
Fix Jason's Bio

### ISSUE THREAD

**Issue by jaboc83** [unsignedbytes/mnrangers#33]
Make it consistent length and style as rest of bios

**Comment by MNRangers** [comment]
Jason Sandifer is a native of St. Paul Minnesota and former student/athlete at Vanguard University where he played point guard. As the head coach of the Minnesota Rangers Jason's duties include individual and team skill development, creating a highly disciplined team that displays self control on and off the court, and motivating players to be and do their best. Jason's vision is to help influence the players to be positive, productive role models in the community.
