### ISSUE TITLE
Update schedule with new team and remove Sioux City

### ISSUE THREAD

**Issue by jaboc83** [unsignedbytes/mnrangers#46]
@mnrangers need new schedule and team info

**Comment by MNRangers** [comment]
[MBLWESTTEAMSContactinformation.doc.docx](https://github.com/unsignedbytes/mnrangers/files/205010/MBLWESTTEAMSContactinformation.doc.docx)

Updated team name- their home location and game time is TBD still

**Comment by MNRangers** [comment]
![clovers](https://cloud.githubusercontent.com/assets/16638123/14291864/0d8cc786-fb2b-11e5-8dbf-ec8aaeafe66a.png)
